#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
sudo apt-get update
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt-get update
sudo apt-get install haproxy=2.4.\* -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver web-01 54.89.109.168:80 check\n\tserver web-02 54.157.141.86:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
