#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
sudo apt-get update
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt-get update
sudo apt-get install haproxy=2.4.\* -y
sudo echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 353097-web-01 54.89.109.168:80 check
        server 353097-web-01 54.157.141.86:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
