#!/usr/bin/env bash
# script
i="1"
sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
hate()
{
echo "I hate the kill command"
sudo rm /var/run/myscript.pid
}
no_love()
{
echo "Y U no love me?!"
}
trap 'hate; exit' SIGTERM
trap 'no_love; exit' SIGINT
trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
while [ $i -eq 1 ]
do
echo "To infinity and beyond"
sleep 2
done
