#!/usr/bin/env bash
# a Bash script that displays numbers

for j in {1..100}
do
if ((j % 15 == 0))
    then
    echo "FizzBuzz"
elif ((j % 5 == 0))
    then
    echo "Buzz"
elif (( j % 3 == 0))
    then
    echo "Fizz"
else
    echo "$j"
fi
done
