#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# but for the 9th iteration, displays Best School and then Hi on a new line.
j="0"
while [ $j -lt 10 ]
do
echo "Best School"
if [ $j -eq 8 ]
then echo "Hi"
fi
j=$((j+1))
done
